### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by frigierim** [egodigital/vscode-powertools#11]
I created a button with the following configuration (in the Workspace settings):

```
"ego.power-tools": {
			
		"commands": 
		{
			"select_platform":
			{
				"script": "commands\\ns-commands.js",
				"button": {
					"text": "Change platform",
					"tooltip": "Change build and deploy platform",
				}
			},
		}
}
```

But when I click on it, I get this error:
![button_error](https://user-images.githubusercontent.com/8074805/52624535-3c758500-2eaf-11e9-8d1b-8307558421aa.jpg)
If I lauch the command from the command palette, though, the command executes correctly.
Am I missing something?

**Comment by ghost** [comment]
@frigierim 

**The bug should be fixed since version 0.21.1.**

**Comment by frigierim** [comment]
Thank you for looking into the issue. I updated the extension, this is the version information:

```
Name: Power Tools
Id: ego-digital.vscode-powertools
Description: A set of useful and handy tools for Visual Studio Code.
Version: 0.21.1
Publisher: e.GO Digital GmbH
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ego-digital.vscode-powertools

```
But I still get the same problem...

**Comment by ghost** [comment]
@frigierim 

Sorry, wrong code ... can you try it again?

**Comment by ghost** [comment]
@frigierim 

**There should be a version 0.21.2 now.**

**Comment by frigierim** [comment]
Thanks, that fixed it!
The ChangeLog page cannot keep up with the speed you create new releases ;)

**Comment by ghost** [comment]
Oh ... thats true :D
